### ISSUE TITLE
child finished with error '256'

### ISSUE THREAD

**Issue by zenlinux** [neeasade/xst#19]
Sorry if this turns out to be a newbie mistake on my end but..

Compiled using make and sudo make install.
Everytime I load it up it crashes with the above error. My googlefu failed to reveal anything that would help me.

Thanks in advance.

uname -r output
4.4.0-59-generic, Lubuntu ( my normal distro is Arch; this is only temporary )

**Comment by pellettiero** [comment]
Hi, do you still have this problem?
If yes, please make sure you updated `xst` to the latest version.

You could also try to get a backtrace with `gdb` (make sure you have installed it):
```
$ ulimit -c unlimited
$ st
<crashes>
$ gdb -q $(which st) /path/to/coredump
gdb> bt full
```

**Comment by mnfcc** [comment]
Sorry about not replying to this earlier. The problem turned out to be the st.shell: /usr/bin/zsh entry in my .Xresources ( from a different computer) . The one I was trying to run st was a brand new install with no zshell. Hence the crash. When I changed st.shell: /bin/bash it worked flawlessly. 
Once again sorry for keeping this open for this long.

**Comment by zenlinux** [comment]
It turned out to be a newbie mistake after all. I was using an older Xresources file (from another computer) which had the st.shell: /usr/bin/zsh . The current computer was a fresh install with no zshell. When I changed st.shell: /bin/bash it started working flawlessly. Sorry for keeping this open for this long.
